-- DEFINO CREACION DE BASE DE DATOS

DROP DATABASE IF EXISTS chipas_ricas_sa ;
CREATE DATABASE chipas_ricas_sa ;

USE chipas_ricas_sa ;


-- CREACION DE TABLAS

CREATE TABLE  RESERVA(
	IDRESERVA 		INT PRIMARY KEY AUTO_INCREMENT
,   IDCLIENTE 		INT
,   IDMESA 			INT
,   IDEMPLEADO 		INT
,   IDTIPORESERVA 	INT
,   FECHA 			DATETIME
,   CANCELACION 	DATETIME DEFAULT NULL
)
COMMENT 'Registra las reservas realizadas por los clientes'
;

CREATE TABLE  CLIENTE(
    IDCLIENTE 		INT PRIMARY KEY AUTO_INCREMENT
,   NOMBRE 			VARCHAR(100) DEFAULT 'USUARIO_UNKNOW'
,   TELEFONO 		VARCHAR(20) NOT NULL
,   CORREO 			VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE  EMPLEADO(
	IDEMPLEADO		INT PRIMARY KEY AUTO_INCREMENT
,	NOMBRE			VARCHAR(100)
,	CORREO			VARCHAR(100) DEFAULT	'chipas_ricas@trial.com'
,	TELEFONO		VARCHAR(100)
,	CUIT			VARCHAR(11)
,	IDRESTAURANTE	INT
);

CREATE TABLE  DUENO(
	IDDUENO			INT PRIMARY KEY AUTO_INCREMENT
,	NOMBRE			VARCHAR(100)
,	CORREO			VARCHAR(100) DEFAULT	'chipas_ricas@trial.com'
,	TELEFONO		VARCHAR(100)
,	CUIT			VARCHAR(11)
);

CREATE TABLE  RESTAURANTE(
	IDRESTAURANTE	INT PRIMARY KEY AUTO_INCREMENT
,	NOMBRE			VARCHAR(100)
,   DIRECCION		VARCHAR(100)
,   TELEFONO		VARCHAR(100)
);

CREATE TABLE  TIPO_RESERVA(
	IDTIPORESERVA	INT PRIMARY KEY AUTO_INCREMENT
,	TIPO			VARCHAR(100)
);

CREATE TABLE  MESA (
	IDMESA 			INT PRIMARY KEY AUTO_INCREMENT
,	IDRESTAURANTE	INT
,	CAPACIDAD		INT
,	DISPONIBILIDAD	BOOLEAN
)
COMMENT "Contiene información sobre las mesas disponibles en cada restaurante"
;


-- CREACION DE LAS FOREIGN KEY

-- FK 
-- EMPLEADO
ALTER TABLE EMPLEADO
	ADD CONSTRAINT FK_EMP_CLIENTE
    FOREIGN KEY (IDRESTAURANTE ) REFERENCES RESTAURANTE(IDRESTAURANTE);

-- MESA
ALTER TABLE MESA
	ADD CONSTRAINT FK_MESA_RESTAURANTE
    FOREIGN KEY (IDRESTAURANTE ) REFERENCES RESTAURANTE(IDRESTAURANTE);


-- RESERVA 

ALTER TABLE RESERVA
	ADD CONSTRAINT FK_RESERVA_RESTAURANTE
    FOREIGN KEY (IDCLIENTE ) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE RESERVA
	ADD CONSTRAINT FK_RESERVA_MESA
    FOREIGN KEY (IDMESA ) REFERENCES MESA(IDMESA);

ALTER TABLE RESERVA
	ADD CONSTRAINT FK_RESERVA_EMPLEADO
    FOREIGN KEY (IDEMPLEADO ) REFERENCES EMPLEADO(IDEMPLEADO );
    
ALTER TABLE RESERVA
	ADD CONSTRAINT FK_RESERVA_TIPORESERVA
    FOREIGN KEY (IDTIPORESERVA ) REFERENCES TIPO_RESERVA(IDTIPORESERVA);


SELECT 
	*
FROM INFORMATION_SCHEMA.TABLES
WHERE table_schema = "chipas_ricas_sa";
